version: "3.8"
services:
  api:
    build: .
    container_name: community-center-api
    volumes:
      - ./src:/app/src
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    env_file:
      - .env
    links:
      - "mongo:mongo"
    depends_on:
      mongo:
        condition: service_healthy

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2024!
      ME_CONFIG_MONGODB_URL: mongodb://admin:community-center-123@mongo:27017/admin
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: community-center-123
    volumes:
      - ~/.docker-conf/mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "admin", "-p", "community-center-123", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 10s
      retries: 2
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge